import type { GetProductionOverviewResponse } from "@/features/production/type/production";

export const productionOverviewMock: GetProductionOverviewResponse = {
  updated_at: "2026-04-06 14:23",
  refresh_interval_minutes: 5,
  summary_stats: [
    { key: "danger_count", label: "품절 위험", value: "1개", tone: "danger" },
    { key: "warning_count", label: "주의 필요", value: "2개", tone: "primary" },
    { key: "safe_count", label: "안전 재고", value: "2개", tone: "success" },
    { key: "chance_loss_saving_total", label: "찬스 로스 절감", value: "23%", tone: "default" },
  ],
  alerts: [
    {
      id: "alert-choco-risk",
      type: "inventory_risk",
      severity: "high",
      title: "긴급: 초코 도넛 재고 소진 1시간 전",
      description: "현재 12개, 1시간 후 2개 예상. 지금 생산하면 찬스 로스 18% 감소 가능",
      sku_id: "choco",
    },
    {
      id: "alert-matcha-speed",
      type: "speed_risk",
      severity: "medium",
      title: "오늘 말차 도넛 소진 속도가 평소보다 빠릅니다",
      description: "평소 대비 30% 빠른 판매 속도 감지. 추가 생산 검토를 권장합니다.",
      sku_id: "matcha",
    },
    {
      id: "alert-material",
      type: "material_risk",
      severity: "medium",
      title: "초콜릿 재료 소진 1시간 전",
      description: "초코 도넛 생산 제한이 예상됩니다. 재료 주문 상태를 함께 확인하세요.",
      ingredient_id: "chocolate",
    },
  ],
  items: [
    {
      sku_id: "choco",
      sku_name: "초코 도넛",
      current_stock: 12,
      forecast_stock_1h: 2,
      avg_first_production_qty_4w: 48,
      avg_first_production_time_4w: "08:30",
      avg_second_production_qty_4w: 24,
      avg_second_production_time_4w: "13:00",
      status: "danger",
      chance_loss_saving_pct: 18,
      speed_alert: true,
      speed_alert_message: "판매 속도 상승 감지",
      material_alert: true,
      material_alert_message: "초콜릿 재료 부족 위험",
      depletion_eta_minutes: 60,
      recommended_production_qty: 48,
      chance_loss_basis_text: "1시간 후 재고 예측 및 4주 평균 손실률 기준",
    },
    {
      sku_id: "strawberry",
      sku_name: "딸기 도넛",
      current_stock: 28,
      forecast_stock_1h: 18,
      avg_first_production_qty_4w: 36,
      avg_first_production_time_4w: "08:45",
      avg_second_production_qty_4w: 24,
      avg_second_production_time_4w: "13:15",
      status: "warning",
      chance_loss_saving_pct: 8,
      recommended_production_qty: 36,
      chance_loss_basis_text: "1시간 후 재고 예측 및 4주 평균 손실률 기준",
    },
    {
      sku_id: "glazed",
      sku_name: "글레이즈드 도넛",
      current_stock: 45,
      forecast_stock_1h: 38,
      avg_first_production_qty_4w: 60,
      avg_first_production_time_4w: "08:15",
      avg_second_production_qty_4w: 30,
      avg_second_production_time_4w: "12:45",
      status: "safe",
      chance_loss_saving_pct: 2,
      recommended_production_qty: 60,
      chance_loss_basis_text: "1시간 후 재고 예측 및 4주 평균 손실률 기준",
    },
    {
      sku_id: "cream",
      sku_name: "크림 도넛",
      current_stock: 31,
      forecast_stock_1h: 24,
      avg_first_production_qty_4w: 42,
      avg_first_production_time_4w: "08:30",
      avg_second_production_qty_4w: 24,
      avg_second_production_time_4w: "13:00",
      status: "safe",
      chance_loss_saving_pct: 3,
      recommended_production_qty: 42,
      chance_loss_basis_text: "1시간 후 재고 예측 및 4주 평균 손실률 기준",
    },
    {
      sku_id: "matcha",
      sku_name: "말차 도넛",
      current_stock: 15,
      forecast_stock_1h: 8,
      avg_first_production_qty_4w: 30,
      avg_first_production_time_4w: "09:00",
      avg_second_production_qty_4w: 18,
      avg_second_production_time_4w: "13:30",
      status: "warning",
      chance_loss_saving_pct: 12,
      speed_alert: true,
      speed_alert_message: "평소 대비 30% 빠른 판매 속도",
      recommended_production_qty: 30,
      chance_loss_basis_text: "1시간 후 재고 예측 및 4주 평균 손실률 기준",
    },
  ],
};
