import type { GetProductionSkuListResponse } from "@/features/production/type/production";

export const productionSkuListMock: GetProductionSkuListResponse = {
  items: [
    {
      sku_id: "choco",
      sku_name: "초코 도넛",
      current_stock: 12,
      forecast_stock_1h: 2,
      avg_first_production_qty_4w: 48,
      avg_first_production_time_4w: "08:30",
      avg_second_production_qty_4w: 24,
      avg_second_production_time_4w: "13:00",
      status: "danger",
      chance_loss_saving_pct: 18,
      speed_alert: true,
      speed_alert_message: "판매 속도 상승 감지",
      material_alert: true,
      material_alert_message: "초콜릿 재료 부족 위험",
      depletion_eta_minutes: 60,
      recommended_production_qty: 48,
      chance_loss_basis_text: "1시간 후 재고 예측 및 4주 평균 손실률 기준",
      decision: {
        risk_level_label: "즉시생산",
        sales_velocity: 1.3,
        tags: ["속도↑", "재료"],
        alert_message: "1시간 내 품절 가능성이 높아 즉시 생산이 필요합니다.",
        can_produce: true,
        predicted_stockout_time: "15:20",
        suggested_production_qty: 48,
        chance_loss_prevented_amount: 54000,
      },
    },
    {
      sku_id: "strawberry",
      sku_name: "딸기 도넛",
      current_stock: 28,
      forecast_stock_1h: 18,
      avg_first_production_qty_4w: 36,
      avg_first_production_time_4w: "08:45",
      avg_second_production_qty_4w: 24,
      avg_second_production_time_4w: "13:15",
      status: "warning",
      chance_loss_saving_pct: 8,
      recommended_production_qty: 36,
      chance_loss_basis_text: "1시간 후 재고 예측 및 4주 평균 손실률 기준",
      decision: {
        risk_level_label: "주의",
        sales_velocity: 1.0,
        tags: [],
        alert_message: "평균 수준의 판매 흐름입니다. 정오 이후 생산 여부를 재확인하세요.",
        can_produce: true,
        predicted_stockout_time: null,
        suggested_production_qty: 36,
        chance_loss_prevented_amount: 12000,
      },
    },
    {
      sku_id: "glazed",
      sku_name: "글레이즈드 도넛",
      current_stock: 45,
      forecast_stock_1h: 38,
      avg_first_production_qty_4w: 60,
      avg_first_production_time_4w: "08:15",
      avg_second_production_qty_4w: 30,
      avg_second_production_time_4w: "12:45",
      status: "safe",
      chance_loss_saving_pct: 2,
      recommended_production_qty: 60,
      chance_loss_basis_text: "1시간 후 재고 예측 및 4주 평균 손실률 기준",
      decision: {
        risk_level_label: "정상",
        sales_velocity: 0.9,
        tags: [],
        alert_message: "현재 재고가 안정적입니다.",
        can_produce: true,
        predicted_stockout_time: null,
        suggested_production_qty: 60,
        chance_loss_prevented_amount: null,
      },
    },
    {
      sku_id: "cream",
      sku_name: "크림 도넛",
      current_stock: 31,
      forecast_stock_1h: 24,
      avg_first_production_qty_4w: 42,
      avg_first_production_time_4w: "08:30",
      avg_second_production_qty_4w: 24,
      avg_second_production_time_4w: "13:00",
      status: "safe",
      chance_loss_saving_pct: 3,
      recommended_production_qty: 42,
      chance_loss_basis_text: "1시간 후 재고 예측 및 4주 평균 손실률 기준",
      decision: {
        risk_level_label: "정상",
        sales_velocity: 0.95,
        tags: [],
        alert_message: "추가 생산 없이도 현재는 안전합니다.",
        can_produce: true,
        predicted_stockout_time: null,
        suggested_production_qty: 42,
        chance_loss_prevented_amount: null,
      },
    },
    {
      sku_id: "matcha",
      sku_name: "말차 도넛",
      current_stock: 15,
      forecast_stock_1h: 8,
      avg_first_production_qty_4w: 30,
      avg_first_production_time_4w: "09:00",
      avg_second_production_qty_4w: 18,
      avg_second_production_time_4w: "13:30",
      status: "warning",
      chance_loss_saving_pct: 12,
      speed_alert: true,
      speed_alert_message: "평소 대비 30% 빠른 판매 속도",
      recommended_production_qty: 30,
      chance_loss_basis_text: "1시간 후 재고 예측 및 4주 평균 손실률 기준",
      decision: {
        risk_level_label: "경고",
        sales_velocity: 1.3,
        tags: ["속도↑"],
        alert_message: "평소보다 판매 속도가 높아 추가 생산 검토가 필요합니다.",
        can_produce: true,
        predicted_stockout_time: "16:10",
        suggested_production_qty: 30,
        chance_loss_prevented_amount: 28000,
      },
    },
  ],
  pagination: {
    page: 1,
    page_size: 20,
    total_items: 5,
    total_pages: 1,
  },
};
